Fix Github CI Build on GCC11
Seems like the newer compilers perform some more aggressive
optimizations which cause the following error to be emitted:

chip8_test.c:1025:48: error: iteration 32 invokes undefined behavior [-Werror=aggressive-loop-optimizations]